title: DataMUX
description: Data Multiplexing for Neural Networks
show_downloads: true
# google_analytics: 
theme: jekyll-theme-cayman
markdown: kramdown

twitter_username: princeton_nlp
title_image: assets/photos/mux_teaser.png

resources:
  paper: https://arxiv.org/abs/2202.09318

kramdown:
  math_engine: mathjax